# /etc/nixos/flake.nix
# Thin wrapper — hardware-configuration.nix stays here; full system config
# is pulled automatically from GitHub on every rebuild.
#
# One-time setup:
#   sudo curl -fsSL -o /etc/nixos/flake.nix \
#     https://raw.githubusercontent.com/VictoryTek/vexos-nix/main/template/etc-nixos-flake.nix
#   sudo nixos-rebuild switch --flake /etc/nixos#vexos-amd
# ════════════════════════════════════════════════════════════════════════════
# BOOTLOADER — configure once for this host, then never touch again.
# Uncomment ONE of the two blocks below that matches your firmware/setup.
# ════════════════════════════════════════════════════════════════════════════
#
# ── Option A: EFI (most modern bare-metal installs) ─────────────────────────
#let
#  bootloaderModule = {
#    boot.loader.systemd-boot.enable      = true;
#    boot.loader.efi.canTouchEfiVariables = true;
#  };
#in
#
# ── Option B: BIOS / Legacy (VirtualBox without EFI, older hardware) ─────────
#let
#  bootloaderModule = {
#    boot.loader.systemd-boot.enable = false;
#    boot.loader.grub = {
#      enable     = true;
#      efiSupport = false;
#      device     = "/dev/sda";  # ← change to your disk (check: lsblk)
#    };
#  };
#in
# ════════════════════════════════════════════════════════════════════════════
let
  # Default: EFI / systemd-boot (modern bare-metal installs).
  # Switch to Option B above if this host uses BIOS firmware (e.g. a BIOS VM).
  bootloaderModule = {
    boot.loader.systemd-boot.enable      = true;
    boot.loader.efi.canTouchEfiVariables = true;
  };
in
{
  inputs = {
    vexos-nix.url = "github:VictoryTek/vexos-nix";

    # Pin nixpkgs to the same version used by the config
    nixpkgs.follows = "vexos-nix/nixpkgs";
  };

  outputs = { self, vexos-nix, nixpkgs }: {

    # ── AMD GPU ──────────────────────────────────────────────────────────────
    nixosConfigurations.vexos-amd = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        bootloaderModule                      # host-specific bootloader (set above)
        ./hardware-configuration.nix          # generated by nixos-generate-config, stays local
        vexos-nix.nixosModules.base           # full desktop + gaming + audio + performance stack
        vexos-nix.nixosModules.gpuAmd         # AMD: RADV, ROCm, LACT
      ];
    };

    # ── NVIDIA GPU ───────────────────────────────────────────────────────────
    nixosConfigurations.vexos-nvidia = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        bootloaderModule
        ./hardware-configuration.nix
        vexos-nix.nixosModules.base
        vexos-nix.nixosModules.gpuNvidia      # NVIDIA: proprietary, modesetting, open kernel modules
      ];
    };

    # ── VM guest (QEMU / VirtualBox) ─────────────────────────────────────────
    nixosConfigurations.vexos-vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        bootloaderModule
        ./hardware-configuration.nix
        vexos-nix.nixosModules.base
        vexos-nix.nixosModules.gpuVm          # QEMU guest agent, VirtualBox additions, SPICE
      ];
    };

  };
}
