# /etc/nixos/flake.nix
# Thin wrapper — hardware-configuration.nix stays here; full system config
# is pulled automatically from GitHub on every rebuild.
#
# ── One-time setup (per machine) ────────────────────────────────────────────
#
#   1. Download this file:
#        sudo curl -fsSL -o /etc/nixos/flake.nix \
#          https://raw.githubusercontent.com/VictoryTek/vexos-nix/main/template/etc-nixos-flake.nix
#
#   2. Apply using the variant that matches your hardware:
#        sudo nixos-rebuild switch --flake /etc/nixos#vexos-desktop-amd
#        sudo nixos-rebuild switch --flake /etc/nixos#vexos-desktop-nvidia
#        sudo nixos-rebuild switch --flake /etc/nixos#vexos-desktop-intel
#        sudo nixos-rebuild switch --flake /etc/nixos#vexos-desktop-vm
#
#      No editing required — all variants are exposed automatically.
#      The chosen variant is written to /etc/nixos/vexos-variant on every
#      build so vexos-updater always knows which target to use.
#
# ── All future rebuilds / updates ───────────────────────────────────────────
#
#   Manually:
#     sudo nixos-rebuild switch --flake /etc/nixos#$(cat /etc/nixos/vexos-variant)
#
#   Via vexos-updater app:
#     The app reads /etc/nixos/vexos-variant and builds the command for you.
#
# ── Switching to a different variant later (e.g. vm → amd) ──────────────────
#
#   Just rebuild with the new variant target:
#     sudo nixos-rebuild switch --flake /etc/nixos#vexos-desktop-amd
#   /etc/nixos/vexos-variant is updated automatically — vexos-updater picks
#   up the new variant from then on.
#
# ── Bootloader ──────────────────────────────────────────────────────────────
#
#   Default: systemd-boot (EFI) — works on all modern hardware and VMs.
#
#   For BIOS/Legacy only: replace the bootloaderModule block below with:
#     bootloaderModule = {
#       boot.loader.systemd-boot.enable = false;
#       boot.loader.grub = {
#         enable     = true;
#         efiSupport = false;
#         device     = "/dev/sda";  # ← verify with: lsblk
#       };
#     };
#
{
  inputs = {
    vexos-nix.url = "github:VictoryTek/vexos-nix";

    # Pin nixpkgs to the same version used by the upstream config.
    nixpkgs.follows = "vexos-nix/nixpkgs";
  };

  outputs = { self, vexos-nix, nixpkgs }:
  let
    # ── Bootloader ──────────────────────────────────────────────────────────
    # EFI / systemd-boot (default — suitable for all modern bare-metal and VM installs).
    # Replace with the BIOS/GRUB stanza from the header comment if needed.
    bootloaderModule = { pkgs, ... }: {
      boot.loader.systemd-boot.enable      = true;
      boot.loader.efi.canTouchEfiVariables = true;
      boot.loader.systemd-boot.extraInstallCommands = ''
        for f in /boot/loader/entries/*.conf; do
          [ -f "$f" ] && ${pkgs.gnused}/bin/sed -i 's/, built on [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}//' "$f"
        done
      '';
    };

    # ── Variant builder ─────────────────────────────────────────────────────
    # Constructs a complete NixOS configuration for a given variant.
    # • hostname   → the variant name, also written to /etc/nixos/vexos-variant
    # • gpuModule  → GPU-specific drivers for this variant (single module or list)
    #
    # Normalises gpuModule to accept either a single module or a list of modules.
    mkVariant = variant: gpuModule: nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules =
        let
          # Convert to list if necessary, preserving backward compatibility
          modules = if builtins.isList gpuModule then gpuModule else [ gpuModule ];
        in
        [
          # Persist the active variant so vexos-updater can read it automatically.
          { environment.etc."nixos/vexos-variant".text = "${variant}\n"; }

          bootloaderModule

          # hardware-configuration.nix is generated by nixos-generate-config and
          # lives in /etc/nixos — it is never committed to the vexos-nix repo.
          ./hardware-configuration.nix

          # Full system stack from the upstream vexos-nix flake.
          vexos-nix.nixosModules.base

          # GPU-specific drivers and settings for this variant.
        ] ++ modules;
    };

  in
  {
    nixosConfigurations = {
      vexos-desktop-amd    = mkVariant "vexos-desktop-amd"    vexos-nix.nixosModules.gpuAmd;
      vexos-desktop-nvidia = mkVariant "vexos-desktop-nvidia" vexos-nix.nixosModules.gpuNvidia;
      vexos-desktop-intel  = mkVariant "vexos-desktop-intel"  vexos-nix.nixosModules.gpuIntel;
      vexos-desktop-vm     = mkVariant "vexos-desktop-vm"     vexos-nix.nixosModules.gpuVm;
    };
  };
}