# /etc/nixos/flake.nix
# Thin wrapper — hardware-configuration.nix stays here; full system config
# is pulled automatically from GitHub on every rebuild.
#
# One-time setup:
#   1. Download this file:
#        sudo curl -fsSL -o /etc/nixos/flake.nix \
#          https://raw.githubusercontent.com/VictoryTek/vexos-nix/main/template/etc-nixos-flake.nix
#   2. Edit the three variables in the let block below (hostname, gpuModule, bootloaderModule)
#   3. Apply: sudo nixos-rebuild switch --flake /etc/nixos
#
# After the first build, all future rebuilds and updates need only:
#   sudo nixos-rebuild switch --flake /etc/nixos
# No #target required — your hostname auto-selects the right config.
{
  inputs = {
    vexos-nix.url = "github:VictoryTek/vexos-nix";

    # Pin nixpkgs to the same version used by the config
    nixpkgs.follows = "vexos-nix/nixpkgs";
  };

  outputs = { self, vexos-nix, nixpkgs }:
  # ════════════════════════════════════════════════════════════════════════════
  # GPU MODULE OPTIONS — pick one, assign to gpuModule in the let block below.
  #   vexos-nix.nixosModules.gpuAmd     → AMD GPU (RADV, ROCm, LACT)
  #   vexos-nix.nixosModules.gpuNvidia  → NVIDIA (proprietary drivers)
  #   vexos-nix.nixosModules.gpuIntel   → Intel iGPU or Arc dGPU
  #   vexos-nix.nixosModules.gpuVm      → VM guest (QEMU / VirtualBox)
  # ════════════════════════════════════════════════════════════════════════════
  #
  # ════════════════════════════════════════════════════════════════════════════
  # BOOTLOADER OPTIONS — pick one, assign to bootloaderModule in the let block.
  #
  # ── Option A: EFI (most modern bare-metal installs) ─────────────────────────
  # bootloaderModule = {
  #   boot.loader.systemd-boot.enable      = true;
  #   boot.loader.efi.canTouchEfiVariables = true;
  # };
  #
  # ── Option B: BIOS / Legacy (VirtualBox without EFI, older hardware) ─────────
  # bootloaderModule = {
  #   boot.loader.systemd-boot.enable = false;
  #   boot.loader.grub = {
  #     enable     = true;
  #     efiSupport = false;
  #     device     = "/dev/sda";  # ← change to your disk (check: lsblk)
  #   };
  # };
  # ════════════════════════════════════════════════════════════════════════════
  let
    # ── Edit these three values once, then never touch this file again ────────

    # Your machine's hostname — any name you want (check current name with: hostname).
    # nixos-rebuild uses this to auto-detect which config to apply.
    hostname = "vexos-amd";

    # Your GPU variant — see GPU MODULE OPTIONS above.
    gpuModule = vexos-nix.nixosModules.gpuAmd;

    # Your bootloader — see BOOTLOADER OPTIONS above (EFI default).
    bootloaderModule = {
      boot.loader.systemd-boot.enable      = true;
      boot.loader.efi.canTouchEfiVariables = true;
    };

    # ── Nothing below this line should need to change ─────────────────────────

  in
  {
    # Single config keyed by your hostname — nixos-rebuild auto-detects it.
    nixosConfigurations.${hostname} = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        { networking.hostName = hostname; }   # binds hostname to this config entry
        bootloaderModule
        ./hardware-configuration.nix          # generated by nixos-generate-config, stays local
        vexos-nix.nixosModules.base           # full desktop + gaming + audio + performance stack
        gpuModule
      ];
    };
  };
}
