# modules/hyprland-desktop.nix
# Hyprland compositor + DankMaterialShell (Quickshell-based desktop shell) for
# the desktop role, started the way Omarchy starts it: no greeter at all, and
# a seamless autologin straight into a UWSM-managed Hyprland session. Active
# only when vexos.desktop.environment == "hyprland" (see
# modules/desktop-environment.nix).
# DE-agnostic content (fonts, printing, Bluetooth, Moonlight, base XDG portal
# enable) comes from modules/desktop-common.nix, imported transitively via
# modules/gnome.nix's import list (present regardless of DE, only its `config`
# is gated). Auto-login is NOT taken from there — see the greetd block below.
#
# No remote-desktop setup here — Sunshine/Moonlight (modules/sunshine.nix)
# is the project's remote-access solution across all desktop environments.
{ config, pkgs, lib, ... }:
let
  isHyprland = config.vexos.desktop.environment == "hyprland";
in
{
  config = lib.mkIf isHyprland {
    programs.hyprland = {
      enable         = true;
      xwayland.enable = true;
      withUWSM       = true;
    };

    # Fall back to software (llvmpipe, via hardware.graphics.enable in
    # modules/gpu.nix) rendering instead of hard-crashing when no working
    # GBM/EGL hardware path is available — the exact symptom on GPUs/VM
    # display devices without real 3D support (e.g. QEMU's default "-vga
    # std"/bochs-drm, as opposed to virtio-gpu with 3D acceleration
    # enabled). Matches upstream guidance for this failure mode:
    # https://github.com/hyprwm/Hyprland/issues/3108
    environment.sessionVariables.WLR_RENDERER_ALLOW_SOFTWARE = "1";

    programs.dms-shell.enable = true;

    # ── Session startup (no greeter) ────────────────────────────────────────
    # Omarchy runs no display manager: omarchy-seamless-login.service takes
    # TTY1 and execs `uwsm start -- hyprland.desktop`, with getty@tty1 masked.
    # greetd's initial_session is the declarative NixOS equivalent — it runs
    # automatically at startup with no greeter and no password prompt — so we
    # get Omarchy's login model without reimplementing its custom VT-handoff
    # helper binary.
    #
    # Deliberately NOT using services.displayManager.dms-greeter (or any other
    # greeter): a greeter is the one piece of Omarchy's stack we were adding
    # that Omarchy itself does not have, and greetd declares
    # `aliases = [ "display-manager.service" ]` with no assertion guarding
    # against a second display manager also claiming that alias.
    #
    # programs.hyprland.withUWSM = true only sets programs.uwsm.enable — it does
    # NOT register Hyprland with UWSM. Session entries are generated solely from
    # programs.uwsm.waylandCompositors, as <name>-uwsm.desktop; nixpkgs' own
    # option docs say "You must configure waylandCompositors suboptions as well
    # so that UWSM knows which compositors to manage." Without this block the
    # attrset is empty, no hyprland-uwsm.desktop is ever produced, and anything
    # asking UWSM to start that session fails with nothing on screen.
    programs.uwsm.waylandCompositors.hyprland = {
      prettyName = "Hyprland";
      binPath    = "${config.programs.hyprland.package}/bin/Hyprland";
    };

    # hyprland-uwsm.desktop is the session entry generated by the
    # waylandCompositors block above.
    # Both default_session and initial_session are set, to the same session.
    # greetd REQUIRES default_session — with only initial_session defined it
    # exits immediately at startup with "default_session contains no command"
    # and nothing ever takes the console (black screen, blinking cursor).
    # initial_session is the boot-time autologin; default_session is what runs
    # afterwards (e.g. on logout). Pointing both at the session — rather than
    # giving default_session a greeter — is what keeps this Omarchy-style:
    # seamless autologin every time, no login screen.
    services.greetd = {
      enable = true;
      settings =
        let
          hyprlandSession = {
            command = "${lib.getExe pkgs.uwsm} start -- hyprland-uwsm.desktop";
            user    = config.vexos.user.name;
          };
        in
        {
          default_session = hyprlandSession;
          initial_session = hyprlandSession;
        };
    };

    xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];

    # ── Wallpaper/branding ──────────────────────────────────────────────────
    # Hyprland has no dconf-equivalent system profile, and NixOS's
    # programs.hyprland does not manage ~/.config/hypr/hyprland.conf (Hyprland
    # generates its own default there on first run). Deploy a default
    # hyprpaper config pointing at the same vexos-wallpapers store path
    # branding-display.nix builds, seeded once on first login so it never
    # clobbers user customisation afterward.
    # NOTE: `exec-once = hyprpaper` must still be added to hyprland.conf by
    # hand (or via a future home-manager-managed hyprland.conf) — this
    # service only seeds hyprpaper's own config file, it does not launch it.
    environment.systemPackages = [ pkgs.hyprpaper ];
    systemd.user.services.vexos-hyprland-wallpaper = {
      description = "Seed default Hyprland wallpaper (once)";
      wantedBy    = [ "graphical-session.target" ];
      after       = [ "graphical-session.target" ];
      serviceConfig = {
        Type            = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        CFG_DIR="$HOME/.config/hypr"
        STAMP="$CFG_DIR/.vexos-wallpaper-seeded"
        [ -f "$STAMP" ] && exit 0
        mkdir -p "$CFG_DIR"
        cat > "$CFG_DIR/hyprpaper.conf" <<EOF
        preload = /run/current-system/sw/share/backgrounds/vexos/vex-bb-dark.jxl
        wallpaper = ,/run/current-system/sw/share/backgrounds/vexos/vex-bb-dark.jxl
        EOF
        touch "$STAMP"
      '';
    };
  };
}
