# modules/network.nix
# Networking: NetworkManager, Avahi/mDNS, firewall baseline, systemd-resolved.
# BBR TCP sysctl tuning is co-located with other kernel tunables in performance.nix.
{ config, pkgs, lib, ... }:
{
  # NetworkManager (primary network management daemon)
  networking.networkmanager.enable = true;

  # ── Prevent hardware-configuration.nix from stealing interfaces ───────────
  # NixOS has two networking backends: NetworkManager and the legacy scripted
  # backend.  NM sets networking.useDHCP = lib.mkDefault false internally, but
  # hardware-configuration.nix generated by nixos-generate-config often sets
  # networking.useDHCP = true (or per-interface useDHCP = true) without
  # lib.mkDefault.  When that wins, the scripted backend re-claims all
  # interfaces and NM marks them "strictly unmanaged" — nmcli device set
  # managed yes is then blocked at the config level.
  # lib.mkForce here wins over any priority hardware-configuration.nix can
  # express, ensuring NM always has full ownership regardless of what the
  # host's generated config says.
  networking.useDHCP = lib.mkForce false;

  # ── Wired fallback profile ────────────────────────────────────────────────
  # A type-only profile with no interface-name binding.  NM activates it on
  # any wired ethernet interface that has no more-specific matching profile.
  #
  # Why this matters: linuxPackages_latest can rename interfaces between
  # kernel versions (e.g. eno1 → enp3s0).  Existing NM profiles bind by
  # interface name and stop matching after a rename; the NIC shows as
  # "unmanaged" in GNOME despite appearing in `ip a`.
  # hardware-configuration.nix's networking.interfaces.* entries are for the
  # legacy scripting backend — NetworkManager ignores them entirely.
  #
  # This profile is written to /etc/NetworkManager/system-connections/ via
  # the ensureProfiles activation service.  autoconnect-priority is set to
  # -999 so any host-specific or manually-created profile (priority 0) wins;
  # this profile only activates as a last resort.
  networking.networkmanager.ensureProfiles.profiles."wired-fallback" = {
    connection = {
      id                   = "Wired Fallback";
      type                 = "ethernet";
      autoconnect          = "true";
      autoconnect-priority = "-999";
    };
    ipv4.method = "auto";
    ipv6 = {
      method        = "auto";
      addr-gen-mode = "stable-privacy";
    };
  };

  # Default hostname — hosts/*.nix can override with a plain assignment.
  networking.hostName = lib.mkDefault "vexos";

  # ── mDNS / Avahi ─────────────────────────────────────────────────────────
  # Required for .local hostname resolution and AirPlay via PipeWire/Avahi.
  services.avahi = {
    enable       = true;
    nssmdns4     = true;     # enables mDNS resolution for .local in NSS
    openFirewall = true;     # opens UDP 5353 (mDNS)
    # Exclude the Tailscale VPN interface from mDNS.
    # mDNS is link-local (224.0.0.251); multicast sent on tailscale0
    # goes into the VPN tunnel, not the LAN.  When Avahi joins the
    # multicast group on tailscale0 it splits its socket attention
    # across eno1 + tailscale0, causing it to miss NAS advertisements
    # that arrive exclusively on the physical LAN interface.  Default
    # NixOS GNOME has no Tailscale interface — this is the exact delta
    # that broke auto-discovery in vexos.
    denyInterfaces = [ "tailscale0" ];
  };

  # ── Firewall baseline ─────────────────────────────────────────────────────
  networking.firewall = {
    enable = true;
    # Steam Remote Play ports are handled by programs.steam.remotePlay.openFirewall in gaming.nix.
  };

  # ── SSH server ───────────────────────────────────────────────────────────
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
    };
  };

  networking.firewall.allowedTCPPorts = [ 22 ];

  # ── Tailscale ─────────────────────────────────────────────────────────────
  services.tailscale = {
    enable = true;
    openFirewall = true;   # opens UDP 41641 (WireGuard/Tailscale data plane)
  };

  # ── DNS resolver ──────────────────────────────────────────────────────────
  services.resolved = {
    enable      = true;
    dnssec      = "allow-downgrade";
    fallbackDns = [ "1.1.1.1" "9.9.9.9" ];
    # Disable resolved's built-in mDNS and LLMNR handlers so they don't
    # conflict with Avahi.  Without this, resolved and Avahi race on mDNS
    # multicast traffic (UDP 5353), causing Avahi's service browser to miss
    # NAS devices advertising _smb._tcp — the root cause of SMB shares not
    # appearing in Nautilus → Network.
    # Reference: https://wiki.archlinux.org/title/Avahi#Installation
    extraConfig = ''
      MulticastDNS=no
      LLMNR=no
    '';
  };

  # ── SMB / CIFS client ────────────────────────────────────────────────────
  # cifs-utils: provides mount.cifs — required to mount SMB/CIFS network shares
  #   Usage: sudo mount -t cifs //server/share /mnt/point -o username=user
  #   Or add to /etc/fstab with _netdev,credentials=/etc/samba/credentials
  # samba: provides smbclient CLI — browse and test SMB shares without mounting
  #   Usage: smbclient -L //server -U user
  # GNOME Files (Nautilus) browses SMB shares natively via GVfs (auto-enabled by GNOME).
  # No inbound firewall ports needed — client-only (outbound to TCP 445).
  environment.systemPackages = with pkgs; [
    cifs-utils  # mount.cifs — mount SMB/CIFS shares from CLI or fstab
  ];
}
