# modules/storage-remote.nix
# Remote storage pool client — the "remote" NAS tier. Universal module: imported
# by every role that supports attaching a network share (desktop, htpc, server,
# headless-server). Inert until at least one mount is declared.
#
# Declares NFS or CIFS/SMB client mounts of shares exported by another machine
# (a NAS unit, another vexos host, ...) so local software — media services on a
# server, or just a file manager on a desktop — can read/write a remote share
# exactly as it would a local disk, without hand-editing /etc/fstab.
#
# Orthogonal to any local backend: a host may use a local ZFS/mergerfs pool,
# attach one or more remote shares, or both. Populated by
# `just attach-remote-storage` into /etc/nixos/storage-remote.nix.
#
# Persistence via NixOS fileSystems (NixOS generates /etc/fstab). Mounts use
# _netdev + nofail + x-systemd.automount so a slow/absent storage server never
# blocks boot — the share mounts lazily on first access instead.
#
# Per the Option B module pattern: options + config, active only when at least
# one remote mount is declared. Inert (empty list) otherwise.
{ config, lib, pkgs, ... }:
let
  cfg = config.vexos.storage.remote;

  remoteModule = lib.types.submodule {
    options = {
      type = lib.mkOption {
        type = lib.types.enum [ "nfs" "cifs" ];
        description = "Remote protocol: nfs or cifs (SMB).";
      };
      server = lib.mkOption {
        type = lib.types.str;
        example = "192.168.1.10";
        description = "Host or IP of the storage server exporting the pool.";
      };
      export = lib.mkOption {
        type = lib.types.str;
        example = "/tank/media";
        description = ''
          NFS export path (e.g. "/tank/media") or CIFS share name (e.g. "media").
        '';
      };
      mountPoint = lib.mkOption {
        type = lib.types.str;
        example = "/mnt/nas-media";
        description = "Local mountpoint for the remote pool.";
      };
      credentialsFile = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "/etc/nixos/secrets/nas-credentials";
        description = ''
          CIFS only: absolute path (on the host, NOT a Nix path — kept out of
          the store) to a file containing `username=` / `password=` lines.
          Required for cifs; ignored for nfs.
        '';
      };
      options = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = ''
          Override mount options. When empty, resilient per-protocol defaults
          are used (_netdev, nofail, x-systemd.automount, timeouts).
        '';
      };
    };
  };

  hasNfs  = lib.any (r: r.type == "nfs")  cfg;
  hasCifs = lib.any (r: r.type == "cifs") cfg;

  baseOpts = [ "_netdev" "nofail" "x-systemd.automount" "x-systemd.mount-timeout=30" "noatime" ];

  effectiveOptions = r:
    if r.options != [ ] then r.options
    else if r.type == "nfs" then [ "nfsvers=4.2" ] ++ baseOpts
    else [ "credentials=${toString r.credentialsFile}" "iocharset=utf8" ] ++ baseOpts;

  remoteFileSystems = builtins.listToAttrs (map (r: {
    name = r.mountPoint;
    value = {
      device = if r.type == "nfs" then "${r.server}:${r.export}" else "//${r.server}/${r.export}";
      fsType = if r.type == "nfs" then "nfs" else "cifs";
      options = effectiveOptions r;
    };
  }) cfg);
in
{
  # Back-compat: the option lived at vexos.server.storage.remote while this was
  # a server-only module. Any already-deployed /etc/nixos/storage-remote.nix
  # still using the old path keeps evaluating (with a deprecation warning) until
  # it is regenerated by `just attach-remote-storage`.
  imports = [
    (lib.mkRenamedOptionModule
      [ "vexos" "server" "storage" "remote" ]
      [ "vexos" "storage" "remote" ])
  ];

  options.vexos.storage.remote = lib.mkOption {
    type = lib.types.listOf remoteModule;
    default = [ ];
    description = ''
      Remote storage shares (NFS/CIFS) to mount from another host. Populated by
      `just attach-remote-storage`.
    '';
  };

  config = lib.mkIf (cfg != [ ]) {
    assertions = [
      {
        assertion = lib.all (r: r.type != "cifs" || r.credentialsFile != null) cfg;
        message = ''
          Every cifs entry in vexos.storage.remote must set
          credentialsFile (an absolute host path to a username=/password= file).
          Anonymous or inline-plaintext CIFS credentials are not allowed.
        '';
      }
    ];

    boot.supportedFilesystems =
      lib.optional hasNfs "nfs" ++ lib.optional hasCifs "cifs";

    environment.systemPackages =
      lib.optional hasNfs pkgs.nfs-utils ++ lib.optional hasCifs pkgs.cifs-utils;

    fileSystems = remoteFileSystems;
  };
}
