{ config, pkgs, lib, ... }:

{
  imports = [
    ./modules/gpu.nix
    ./modules/branding.nix
    ./modules/network.nix
    ./modules/packages-common.nix
    ./modules/system.nix
    ./modules/server       # Optional server services (vexos.server.*.enable)
  ];

  # ---------- Hostname ----------
  networking.hostName = lib.mkDefault "vexos";

  # ---------- Time / Locale ----------
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";

  # ---------- Console ----------
  # When a KMS GPU driver initialises, the DRM framebuffer console takes over at
  # native display resolution (e.g. 1920×1080 or 4K).  At that resolution the
  # default 8×8 kernel font renders as ~2px tall characters — invisible on any
  # normal monitor.  The hardware cursor blink is still drawn by display hardware
  # and remains visible, producing the "black screen with blinking cursor" symptom.
  #
  # earlySetup loads the font in stage 1 (initrd) before DRM takes over.
  # console.packages makes terminus_font available; ter-v32n (16×32) is legible
  # at 1080p and 4K without requiring a compositor.
  console.earlySetup = true;
  console.packages   = [ pkgs.terminus_font ];
  console.font       = "ter-v32n";

  # ---------- Display manager ----------
  # Explicitly disable X11 and GDM.  hardware-configuration.nix generated by
  # the NixOS graphical installer may contain services.xserver.enable = true
  # or services.xserver.videoDrivers which would survive nixos-rebuild switch
  # and prevent a clean headless boot.
  services.xserver.enable = lib.mkForce false;

  # ---------- Branding ----------
  # Reuse the "server" role to pick up existing server/ branding assets
  # (pixmaps, background logos, Plymouth watermark, wallpapers).
  # Override distroName to distinguish from the GUI server role.
  vexos.branding.role     = "server";
  system.nixos.distroName = lib.mkOverride 500 "VexOS Headless Server";

  # ---------- Users ----------
  users.users.nimda = {
    isNormalUser = true;
    description  = "nimda";
    extraGroups  = [
      "wheel"
      "networkmanager"
    ];
  };

  # ---------- Nix settings ----------
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    trusted-users         = [ "root" "@wheel" ];
    auto-optimise-store   = true;
    substituters = [
      "https://cache.nixos.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];
    max-jobs    = 1;
    cores       = 0;
    min-free    = 1073741824;   # 1 GiB
    max-free    = 5368709120;   # 5 GiB

    download-buffer-size = 524288000; # 500 MiB

    keep-outputs     = false;
    keep-derivations = false;
  };

  nix.daemonCPUSchedPolicy = "idle";
  nix.daemonIOSchedClass   = "idle";

  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 7d";
  };

  nix.optimise = {
    automatic = true;
    dates     = [ "weekly" ];
  };

  # ---------- Nixpkgs ----------
  # allowUnfree required for NVIDIA proprietary drivers via modules/gpu/nvidia.nix.
  nixpkgs.config.allowUnfree = true;

  # ---------- State version ----------
  # Set once at install time — do not change after initial deployment.
  system.stateVersion = "25.11";
}
