{ config, pkgs, lib, ... }:

{
  imports = [
    ./modules/gnome.nix
    ./modules/gnome-stateless.nix
    ./modules/audio.nix
    ./modules/gpu.nix
    ./modules/flatpak.nix
    ./modules/network.nix
    ./modules/network-desktop.nix   # samba CLI
    ./modules/packages-common.nix
    ./modules/packages-desktop.nix
    ./modules/branding.nix
    ./modules/branding-display.nix  # wallpapers, GDM logo/dconf
    ./modules/system.nix
    ./modules/system-latest-kernel.nix  # Linux 7.x (linuxPackages_latest)
    ./modules/system-nosleep.nix    # disable sleep/suspend/hibernate on stateless
    ./modules/security.nix          # AppArmor MAC baseline (all roles)
    ./modules/impermanence.nix
    ./modules/nix.nix
    ./modules/nix-stateless.nix     # 7-day GC retention (state resets on reboot)
    ./modules/locale.nix
    ./modules/users.nix
    ./modules/asus-opt.nix
    ./modules/boot-discovery.nix
  ];

  # ---------- Branding ----------
  vexos.branding.role  = "stateless";
  boot.plymouth.enable = true;   # graphical boot splash

  # ---------- Users ----------
  # Primary account is locked by default ("!" shadow hash = no password accepted).
  # stateless-setup.sh and migrate-to-stateless.sh both write a real password
  # hash to /etc/nixos/stateless-user-override.nix (persisted to @persistent)
  # before the first build.  The variant builder conditionally imports that
  # file; without it, the system builds but no user login is possible, which
  # forces the operator to run a setup script before first use.
  users.users.${config.vexos.user.name}.hashedPassword = lib.mkDefault "!";

  # Root gets an empty password (no password required) so that the systemd
  # initrd's sulogin can open an emergency shell when boot fails.
  # With users.mutableUsers = false (set by impermanence.nix), root's shadow
  # entry is generated from config; without this line root is locked ("!!")
  # and sulogin refuses to open the console — making failures undebuggable.
  # An empty hash is safe here: the stateless root is a personal ephemeral
  # machine; all user-facing state resets on every reboot by design.
  users.users.root.hashedPassword = "";

  # ---------- Impermanence ----------
  # Enable tmpfs-rooted ephemeral filesystem for the stateless role.
  # / is wiped on every reboot; only /nix and /persistent survive.
  # Filesystem impermanence: / is mounted as tmpfs by this module.
  # Run scripts/stateless-setup.sh to format the disk before first deploy.
  vexos.impermanence.enable = true;

  # ---------- System packages ----------
  # tor-browser: installed system-wide (not via Home Manager) so torbrowser.desktop
  # lands in /run/current-system/sw/share/applications/ and is always visible to
  # GNOME regardless of Home Manager activation timing on the fresh tmpfs home.
  environment.systemPackages = [
    pkgs.tor-browser
  ];

  # ---------- Flatpak ----------
  # Prevent GIMP from being installed on stateless. It is never in
  # defaultApps but may be present from a manual install or prior session.
  # Desktop-role extras are also excluded so they are actively uninstalled
  # if this machine was previously running the desktop configuration and
  # /var/lib/flatpak (persisted by impermanence) carries stale installs.
  vexos.flatpak.excludeApps = [
    "org.gimp.GIMP"
    # Desktop-role gaming / utility flatpaks
    "org.prismlauncher.PrismLauncher"
    "com.vysp3r.ProtonPlus"
    "net.lutris.Lutris"
    # Desktop-role dev / misc flatpaks
    "io.github.pol_rivero.github-desktop-plus"
    "com.ranfdev.DistroShelf"
  ];

  # ---------- Password reminder ----------
  # Warn during every nixos-rebuild if the primary user account is still locked
  # (hashedPassword = "!").  An operator must run scripts/stateless-setup.sh
  # (or write /etc/nixos/stateless-user-override.nix manually) before first
  # login on a stateless host.  Using warnings (not assertions) keeps the
  # configuration evaluable on dev machines that have no user override file,
  # while still alerting the operator at build time.
  warnings = lib.optional
    (config.users.users.${config.vexos.user.name}.hashedPassword == "!")
    ''
      The primary user account (${config.vexos.user.name}) still has a locked password ("!").
      Run scripts/stateless-setup.sh to set a password, or manually create
      /etc/nixos/stateless-user-override.nix with a hashed password generated by:
        mkpasswd -m sha-512
    '';

  # ---------- State version ----------
  # This value determines the NixOS release from which the default
  # settings for stateful data (like file locations) were taken.
  # Do NOT change this after initial install — it stays at the version
  # NixOS was first installed with, regardless of nixpkgs channel upgrades.
  system.stateVersion = "25.11";
}
