{ config, pkgs, lib, ... }:

{
  imports = [
    ./modules/gpu.nix
    ./modules/branding.nix
    ./modules/network.nix
    ./modules/packages-common.nix
    ./modules/system.nix
    ./modules/server       # Optional server services (vexos.server.*.enable)
    ./modules/zfs-server.nix
    ./modules/nix.nix
    ./modules/nix-server.nix        # 30-day GC retention (production server standard)
    ./modules/locale.nix
    ./modules/users.nix
  ];

  # ---------- Console ----------
  # When a KMS GPU driver initialises, the DRM framebuffer console takes over at
  # native display resolution (e.g. 1920×1080 or 4K).  At that resolution the
  # default 8×8 kernel font renders as ~2px tall characters — invisible on any
  # normal monitor.  The hardware cursor blink is still drawn by display hardware
  # and remains visible, producing the "black screen with blinking cursor" symptom.
  #
  # earlySetup loads the font in stage 1 (initrd) before DRM takes over.
  # console.packages makes terminus_font available; ter-v32n (16×32) is legible
  # at 1080p and 4K without requiring a compositor.
  console.earlySetup = true;
  console.packages   = [ pkgs.terminus_font ];
  console.font       = "ter-v32n";

  # ---------- Display manager ----------
  # Explicitly disable X11 and GDM.  hardware-configuration.nix generated by
  # the NixOS graphical installer may contain services.xserver.enable = true
  # or services.xserver.videoDrivers which would survive nixos-rebuild switch
  # and prevent a clean headless boot.
  services.xserver.enable = lib.mkForce false;

  # ---------- Branding ----------
  # Use the "headless-server" role; branding.nix maps it to the existing
  # files/.../server/ asset directories via its `assetRole` let-binding,
  # so no asset duplication is required while keeping role identity distinct.
  # Override distroName to distinguish from the GUI server role.
  vexos.branding.role     = "headless-server";
  system.nixos.distroName = lib.mkOverride 500 "VexOS Headless Server";

  # ---------- State version ----------
  # Set once at install time — do not change after initial deployment.
  system.stateVersion = "25.11";
}
