{
  description = "vexos-nix — Personal NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # nixpkgs-unstable: used to supply latest GNOME application packages in
    # modules/gnome.nix via the pkgs.unstable overlay.
    # Do NOT add inputs.nixpkgs-unstable.follows = "nixpkgs" — that would
    # pin unstable to the stable revision, defeating its purpose.
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

    # nix-gaming: low-latency PipeWire module, SteamOS platform optimisations, Wine-GE packages
    nix-gaming = {
      url = "github:fufexan/nix-gaming";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # home-manager: optional, for user-level dotfiles (future use)
    home-manager = {
      url = "github:nix-community/home-manager/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # nix-community/impermanence: declarative persistence for tmpfs-rooted systems.
    # Used exclusively by the stateless role (configuration-stateless.nix).
    # impermanence has no nixpkgs dependency — follows not required.
    impermanence.url = "github:nix-community/impermanence";

    # Up — GTK4 + libadwaita system update GUI (all roles and variants).
    up = {
      url = "github:VictoryTek/Up";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, nix-gaming, home-manager, impermanence, up, ... }@inputs:
  let
    system = "x86_64-linux";

    # Inline NixOS module: exposes pkgs.unstable.* sourced from nixpkgs-unstable.
    # Used in modules/gnome.nix to pin GNOME application tools to latest.
    unstableOverlayModule = {
      nixpkgs.overlays = [
        (final: prev: {
          unstable = import nixpkgs-unstable {
            inherit (final) config;
            inherit (final.stdenv.hostPlatform) system;
          };
        })
      ];
    };

    # Home Manager: user-level packages, dotfiles, GNOME dconf settings and theming.
    homeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;  # share nixpkgs instance (+ overlays) with the system
        useUserPackages  = true;  # install user packages into /etc/profiles instead of ~/.nix-profile
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home.nix;
        # Prevents activation abort when managed files (e.g. ~/.bashrc) already
        # exist as regular files on the host.  Conflicting files are renamed to
        # *.backup instead of causing checkLinkTargets to exit non-zero.
        backupFileExtension = "backup";
      };
    };

    # Modules shared across desktop/stateless configurations (includes home-manager)
    commonModules = [
      # Hardware config generated by nixos-generate-config (lives on the host, NOT in this repo)
      /etc/nixos/hardware-configuration.nix

      unstableOverlayModule
      homeManagerModule
      { environment.systemPackages = [ up.packages.x86_64-linux.default ]; }
    ];

    # Modules for server/htpc roles — no home-manager
    minimalModules = [
      /etc/nixos/hardware-configuration.nix
      unstableOverlayModule
      { environment.systemPackages = [ up.packages.x86_64-linux.default ]; }
    ];
  in
  {
    # ── AMD GPU build ────────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-amd
    nixosConfigurations.vexos-desktop-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia
    nixosConfigurations.vexos-desktop-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build — Maxwell/Pascal/Volta legacy LTS (535.x branch) ─────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia-legacy535
    nixosConfigurations.vexos-desktop-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/desktop-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build — Kepler legacy (GeForce 600/700 series) ────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia-legacy470
    nixosConfigurations.vexos-desktop-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/desktop-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build — Fermi legacy (GeForce 400/500 series) ─────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia-legacy390
    nixosConfigurations.vexos-desktop-nvidia-legacy390 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/desktop-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_390"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── VM guest build (QEMU/KVM + VirtualBox) ───────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-vm
    nixosConfigurations.vexos-desktop-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Intel GPU build ──────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-intel
    nixosConfigurations.vexos-desktop-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless AMD build ────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-amd
    nixosConfigurations.vexos-stateless-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-amd.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build ─────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia
    nixosConfigurations.vexos-stateless-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build — Maxwell/Pascal/Volta legacy LTS (535.x branch) 
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia-legacy535
    nixosConfigurations.vexos-stateless-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build — Kepler legacy (GeForce 600/700 series) ───────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia-legacy470
    nixosConfigurations.vexos-stateless-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build — Fermi legacy (GeForce 400/500 series) ────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia-legacy390
    nixosConfigurations.vexos-stateless-nvidia-legacy390 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
        { vexos.gpu.nvidiaDriverVariant = "legacy_390"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless Intel build ──────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-intel
    nixosConfigurations.vexos-stateless-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-intel.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless VM build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-vm
    nixosConfigurations.vexos-stateless-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/stateless-vm.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Server AMD build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-amd
    nixosConfigurations.vexos-server-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/server-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Server NVIDIA build ──────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-nvidia
    nixosConfigurations.vexos-server-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/server-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Server Intel build ───────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-intel
    nixosConfigurations.vexos-server-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/server-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Server VM build ──────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-vm
    nixosConfigurations.vexos-server-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/server-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC AMD build ───────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-amd
    nixosConfigurations.vexos-htpc-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/htpc-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build ────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia
    nixosConfigurations.vexos-htpc-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/htpc-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build — Maxwell/Pascal/Volta legacy LTS (535.x branch) ────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia-legacy535
    nixosConfigurations.vexos-htpc-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [
        ./hosts/htpc-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build — Kepler legacy (GeForce 600/700 series) ───────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia-legacy470
    nixosConfigurations.vexos-htpc-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [
        ./hosts/htpc-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build — Fermi legacy (GeForce 400/500 series) ────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia-legacy390
    nixosConfigurations.vexos-htpc-nvidia-legacy390 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [
        ./hosts/htpc-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_390"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC Intel build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-intel
    nixosConfigurations.vexos-htpc-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/htpc-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC VM build ────────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-vm
    nixosConfigurations.vexos-htpc-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = minimalModules ++ [ ./hosts/htpc-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NixOS modules (consumed by /etc/nixos/flake.nix on the host) ─────────
    # The thin wrapper at /etc/nixos/flake.nix imports these instead of
    # building directly from the repo, so hardware-configuration.nix never
    # needs to leave /etc/nixos.
    nixosModules = {
      # Full stack: desktop + gaming + audio + performance + controllers + network + flatpak
      # Also bundles nix-gaming low-latency PipeWire and Steam platform optimisations.
      base = { ... }: {
        imports = [
          nix-gaming.nixosModules.pipewireLowLatency
          home-manager.nixosModules.home-manager
          ./configuration.nix
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home.nix;
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };

      # Stateless stack: minimal, without gaming/development/virtualization/asus.
      # Suitable for a clean daily-driver focused on stateless and basic productivity.
      statelessBase = { lib, ... }: {
        imports = [
          nix-gaming.nixosModules.pipewireLowLatency
          home-manager.nixosModules.home-manager
          impermanence.nixosModules.impermanence
          ./configuration-stateless.nix
          ./modules/stateless-disk.nix
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home.nix;
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
        vexos.stateless.disk = {
          enable     = true;
          device     = lib.mkDefault "/dev/nvme0n1";
        };
      };

      # Guard: disable VirtualBox guest additions on all bare-metal variants.
      # hardware-configuration.nix generated inside a VirtualBox VM sets
      # virtualisation.virtualbox.guest.enable = true; lib.mkForce false here
      # ensures that value can never survive into a non-VM build, preventing
      # VirtualBox-GuestAdditions from attempting to compile against a kernel
      # that has removed the required DRM symbols (Linux 6.12+).
      gpuAmd = { lib, ... }: {
        imports = [ ./modules/gpu/amd.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuNvidia = { lib, ... }: {
        imports = [ ./modules/gpu/nvidia.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuIntel = { lib, ... }: {
        imports = [ ./modules/gpu/intel.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuVm = { ... }: {
        imports = [ ./modules/gpu/vm.nix ];
      };
      statelessGpuVm = { lib, ... }: {
        imports = [ ./modules/gpu/vm.nix ];
        vexos.stateless.disk.device = lib.mkForce "/dev/vda";
      };
      asus      = ./modules/asus.nix;

      # HTPC stack: media-centre focused, no gaming/development/virtualization.
      htpcBase = { ... }: {
        imports = [ ./configuration-htpc.nix ];
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };

      # Server stack: headless, no gaming/development/virtualization.
      serverBase = { ... }: {
        imports = [ ./configuration-server.nix ];
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };
    };
  };
}
