{
  description = "vexos-nix — Personal NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";

    # nix-gaming: low-latency PipeWire module, SteamOS platform optimisations, Wine-GE packages
    nix-gaming = {
      url = "github:fufexan/nix-gaming";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # home-manager: optional, for user-level dotfiles (future use)
    home-manager = {
      url = "github:nix-community/home-manager/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, nix-gaming, ... }@inputs:
  let
    system = "x86_64-linux";

    # Modules shared across all three configurations
    commonModules = [
      # Hardware config generated by nixos-generate-config (lives on the host, NOT in this repo)
      /etc/nixos/hardware-configuration.nix

      # nix-gaming: declarative low-latency PipeWire tuning
      nix-gaming.nixosModules.pipewireLowLatency
    ];
  in
  {
    # ── AMD GPU build ────────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-amd
    nixosConfigurations.vexos-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-nvidia
    nixosConfigurations.vexos-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── VM guest build (QEMU/KVM + VirtualBox) ───────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-vm
    nixosConfigurations.vexos-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NixOS modules (consumed by /etc/nixos/flake.nix on the host) ─────────
    # The thin wrapper at /etc/nixos/flake.nix imports these instead of
    # building directly from the repo, so hardware-configuration.nix never
    # needs to leave /etc/nixos.
    nixosModules = {
      # Full stack: desktop + gaming + audio + performance + controllers + network + flatpak
      # Also bundles nix-gaming low-latency PipeWire and Steam platform optimisations.
      base = { ... }: {
        imports = [
          nix-gaming.nixosModules.pipewireLowLatency
          ./configuration.nix
        ];
      };

      gpuAmd    = ./modules/gpu/amd.nix;
      gpuNvidia = ./modules/gpu/nvidia.nix;
      gpuVm     = ./modules/gpu/vm.nix;
    };
  };
}
