{
  description = "vexos-nix — Personal NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

    # nixpkgs-unstable: used to supply latest GNOME application packages in
    # modules/gnome.nix via the pkgs.unstable overlay.
    # Do NOT add inputs.nixpkgs-unstable.follows = "nixpkgs" — that would
    # pin unstable to the stable revision, defeating its purpose.
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

    # home-manager: optional, for user-level dotfiles (future use)
    home-manager = {
      url = "github:nix-community/home-manager/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # nix-community/impermanence: declarative persistence for tmpfs-rooted systems.
    # Used exclusively by the stateless role (configuration-stateless.nix).
    # impermanence has no nixpkgs dependency — follows not required.
    impermanence.url = "github:nix-community/impermanence";

    # Up — GTK4 + libadwaita system update GUI (all roles and variants).
    up = {
      url = "github:VictoryTek/Up";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # proxmox-nixos: Proxmox VE hypervisor on NixOS. Used by modules/server/proxmox.nix.
    # Do NOT add inputs.proxmox-nixos.inputs.nixpkgs.follows = "nixpkgs" — the upstream
    # flake manages its own nixpkgs-stable pin; overriding it breaks package builds.
    proxmox-nixos.url = "github:SaumonNet/proxmox-nixos";
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, home-manager, impermanence, up, ... }@inputs:
  let
    system = "x86_64-linux";

    # Inline NixOS module: exposes pkgs.unstable.* sourced from nixpkgs-unstable.
    # Used in modules/gnome.nix to pin GNOME application tools to latest.
    unstableOverlayModule = {
      nixpkgs.overlays = [
        (final: prev: {
          unstable = import nixpkgs-unstable {
            inherit (final) config;
            inherit (final.stdenv.hostPlatform) system;
          };
        })
      ];
    };

    # Home Manager: user-level packages, dotfiles, GNOME dconf settings and theming.
    homeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;  # share nixpkgs instance (+ overlays) with the system
        useUserPackages  = true;  # install user packages into /etc/profiles instead of ~/.nix-profile
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home-desktop.nix;
        # Prevents activation abort when managed files (e.g. ~/.bashrc) already
        # exist as regular files on the host.  Conflicting files are renamed to
        # *.backup instead of causing checkLinkTargets to exit non-zero.
        backupFileExtension = "backup";
      };
    };

    # Modules shared across desktop configurations (includes home-manager)
    commonModules = [
      # Hardware config generated by nixos-generate-config (lives on the host, NOT in this repo)
      /etc/nixos/hardware-configuration.nix

      unstableOverlayModule
      homeManagerModule
      upModule
    ];

    # GUI update app — only for roles with a display (desktop, htpc, GUI server, stateless)
    upModule = { environment.systemPackages = [ up.packages.x86_64-linux.default ]; };

    # Modules for server/htpc roles — no home-manager
    minimalModules = [
      /etc/nixos/hardware-configuration.nix
      unstableOverlayModule
    ];

    # Home Manager: HTPC-specific user environment (wallpapers, dconf wallpaper settings).
    htpcHomeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;
        useUserPackages  = true;
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home-htpc.nix;
        backupFileExtension = "backup";
      };
    };

    # Home Manager: Stateless-specific user environment (no gaming/dev, same shell/theming as desktop).
    statelessHomeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;
        useUserPackages  = true;
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home-stateless.nix;
        backupFileExtension = "backup";
      };
    };

    # Home Manager: GUI Server-specific user environment (shell/theming, no gaming/dev).
    serverHomeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;
        useUserPackages  = true;
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home-server.nix;
        backupFileExtension = "backup";
      };
    };

    # Modules for HTPC role — minimal + home-manager for wallpaper/theming.
    htpcModules = minimalModules ++ [ upModule htpcHomeManagerModule ];

    # Modules for stateless role — base stack + stateless-specific home-manager.
    statelessModules = [
      /etc/nixos/hardware-configuration.nix
      unstableOverlayModule
      statelessHomeManagerModule
      upModule
    ];

    # Modules for GUI Server role — minimal + server-specific home-manager.
    # Optionally loads /etc/nixos/server-services.nix for modular service toggles.
    serverServicesModule =
      let path = /etc/nixos/server-services.nix;
      in if builtins.pathExists path then [ path ] else [];
    serverModules = minimalModules ++ [ upModule serverHomeManagerModule ] ++ serverServicesModule;

    # Home Manager: Headless Server-specific user environment (shell tools only, no GNOME).
    headlessServerHomeManagerModule = {
      imports = [ home-manager.nixosModules.home-manager ];
      home-manager = {
        useGlobalPkgs    = true;
        useUserPackages  = true;
        extraSpecialArgs = { inherit inputs; };
        users.nimda      = import ./home-headless-server.nix;
        backupFileExtension = "backup";
      };
    };

    # Modules for headless server role — minimal + headless-server-specific home-manager.
    # Reuses serverServicesModule so /etc/nixos/server-services.nix opt-in services
    # work identically on both the GUI server and headless server roles.
    headlessServerModules = minimalModules ++ [ headlessServerHomeManagerModule ] ++ serverServicesModule;
  in
  {
    # ── AMD GPU build ────────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-amd
    nixosConfigurations.vexos-desktop-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia
    nixosConfigurations.vexos-desktop-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build — Maxwell/Pascal/Volta legacy LTS (535.x branch) ─────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia-legacy535
    nixosConfigurations.vexos-desktop-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/desktop-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── NVIDIA GPU build — Kepler legacy (GeForce 600/700 series) ────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-nvidia-legacy470
    nixosConfigurations.vexos-desktop-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [
        ./hosts/desktop-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── VM guest build (QEMU/KVM + VirtualBox) ───────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-vm
    nixosConfigurations.vexos-desktop-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Intel GPU build ──────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-desktop-intel
    nixosConfigurations.vexos-desktop-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = commonModules ++ [ ./hosts/desktop-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless AMD build ────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-amd
    nixosConfigurations.vexos-stateless-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-amd.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build ─────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia
    nixosConfigurations.vexos-stateless-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build — Maxwell/Pascal/Volta legacy LTS (535.x branch) 
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia-legacy535
    nixosConfigurations.vexos-stateless-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless NVIDIA build — Kepler legacy (GeForce 600/700 series) ───────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-nvidia-legacy470
    nixosConfigurations.vexos-stateless-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-nvidia.nix
        impermanence.nixosModules.impermanence
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless Intel build ──────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-intel
    nixosConfigurations.vexos-stateless-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-intel.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── Stateless VM build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-stateless-vm
    nixosConfigurations.vexos-stateless-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = statelessModules ++ [
        ./hosts/stateless-vm.nix
        impermanence.nixosModules.impermanence
      ];
      specialArgs = { inherit inputs; };
    };

    # ── GUI Server AMD build ──────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-amd
    nixosConfigurations.vexos-server-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = serverModules ++ [ ./hosts/server-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── GUI Server NVIDIA build ────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-nvidia
    nixosConfigurations.vexos-server-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = serverModules ++ [ ./hosts/server-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── GUI Server Intel build ───────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-intel
    nixosConfigurations.vexos-server-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = serverModules ++ [ ./hosts/server-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── GUI Server VM build ────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-server-vm
    nixosConfigurations.vexos-server-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = serverModules ++ [ ./hosts/server-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Headless Server AMD build ──────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-headless-server-amd
    nixosConfigurations.vexos-headless-server-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = headlessServerModules ++ [ ./hosts/headless-server-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Headless Server NVIDIA build ───────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-headless-server-nvidia
    nixosConfigurations.vexos-headless-server-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = headlessServerModules ++ [ ./hosts/headless-server-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Headless Server Intel build ────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-headless-server-intel
    nixosConfigurations.vexos-headless-server-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = headlessServerModules ++ [ ./hosts/headless-server-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── Headless Server VM build ───────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-headless-server-vm
    nixosConfigurations.vexos-headless-server-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = headlessServerModules ++ [ ./hosts/headless-server-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC AMD build ───────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-amd
    nixosConfigurations.vexos-htpc-amd = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [ ./hosts/htpc-amd.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build ────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia
    nixosConfigurations.vexos-htpc-nvidia = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [ ./hosts/htpc-nvidia.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build — Maxwell/Pascal/Volta legacy LTS (535.x branch) ────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia-legacy535
    nixosConfigurations.vexos-htpc-nvidia-legacy535 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [
        ./hosts/htpc-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_535"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC NVIDIA build — Kepler legacy (GeForce 600/700 series) ───────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-nvidia-legacy470
    nixosConfigurations.vexos-htpc-nvidia-legacy470 = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [
        ./hosts/htpc-nvidia.nix
        { vexos.gpu.nvidiaDriverVariant = "legacy_470"; }
      ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC Intel build ─────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-intel
    nixosConfigurations.vexos-htpc-intel = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [ ./hosts/htpc-intel.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── HTPC VM build ────────────────────────────────────────────────────────
    # sudo nixos-rebuild switch --flake .#vexos-htpc-vm
    nixosConfigurations.vexos-htpc-vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = htpcModules ++ [ ./hosts/htpc-vm.nix ];
      specialArgs = { inherit inputs; };
    };

    # ── NixOS modules (consumed by /etc/nixos/flake.nix on the host) ─────────
    # The thin wrapper at /etc/nixos/flake.nix imports these instead of
    # building directly from the repo, so hardware-configuration.nix never
    # needs to leave /etc/nixos.
    nixosModules = {
      # Full stack: desktop + gaming + audio + performance + controllers + network + flatpak
      base = { ... }: {
        imports = [
          home-manager.nixosModules.home-manager
          ./configuration-desktop.nix
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home-desktop.nix;
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };

      # Stateless stack: minimal, without gaming/development/virtualization/asus.
      # Suitable for a clean daily-driver focused on stateless and basic productivity.
      statelessBase = { lib, ... }: {
        imports = [
          home-manager.nixosModules.home-manager
          impermanence.nixosModules.impermanence
          ./configuration-stateless.nix
          ./modules/stateless-disk.nix
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home-desktop.nix;
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
        vexos.stateless.disk = {
          enable     = true;
          device     = lib.mkDefault "/dev/nvme0n1";
        };
      };

      # Guard: disable VirtualBox guest additions on all bare-metal variants.
      # hardware-configuration.nix generated inside a VirtualBox VM sets
      # virtualisation.virtualbox.guest.enable = true; lib.mkForce false here
      # ensures that value can never survive into a non-VM build, preventing
      # VirtualBox-GuestAdditions from attempting to compile against a kernel
      # that has removed the required DRM symbols (Linux 6.12+).
      gpuAmd = { lib, ... }: {
        imports = [ ./modules/gpu/amd.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuNvidia = { lib, ... }: {
        imports = [ ./modules/gpu/nvidia.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuIntel = { lib, ... }: {
        imports = [ ./modules/gpu/intel.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };

      # Headless server GPU modules: compute/VA-API without early KMS / display init.
      gpuAmdHeadless = { lib, ... }: {
        imports = [ ./modules/gpu/amd-headless.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuNvidiaHeadless = { lib, ... }: {
        imports = [ ./modules/gpu/nvidia-headless.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuIntelHeadless = { lib, ... }: {
        imports = [ ./modules/gpu/intel-headless.nix ];
        virtualisation.virtualbox.guest.enable = lib.mkForce false;
      };
      gpuVm = { ... }: {
        imports = [ ./modules/gpu/vm.nix ];
      };
      statelessGpuVm = { lib, ... }: {
        imports = [ ./modules/gpu/vm.nix ];
        vexos.stateless.disk.device = lib.mkForce "/dev/vda";
      };
      asus      = ./modules/asus.nix;

      # HTPC stack: media-centre focused, no gaming/development/virtualization.
      htpcBase = { ... }: {
        imports = [
          home-manager.nixosModules.home-manager
          ./configuration-htpc.nix
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home-htpc.nix;
          backupFileExtension = "backup";
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };

      # Server stack: GUI server, no gaming/development/virtualization.
      serverBase = { ... }: {
        imports = [
          home-manager.nixosModules.home-manager
          ./configuration-server.nix
          # Import here (not in modules/server/proxmox.nix) to avoid infinite
          # recursion — `imports` cannot safely reference _module.args.
          inputs.proxmox-nixos.nixosModules.proxmox-ve
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home-server.nix;
          backupFileExtension = "backup";
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        environment.systemPackages = [ up.packages.x86_64-linux.default ];
      };

      # Headless server stack: no GUI, no audio, no Flatpak.
      # Suitable for production servers accessed via SSH.
      headlessServerBase = { ... }: {
        imports = [
          home-manager.nixosModules.home-manager
          ./configuration-headless-server.nix
          # Import here (not in modules/server/proxmox.nix) to avoid infinite
          # recursion — `imports` cannot safely reference _module.args.
          inputs.proxmox-nixos.nixosModules.proxmox-ve
        ];
        home-manager = {
          useGlobalPkgs    = true;
          useUserPackages  = true;
          extraSpecialArgs = { inherit inputs; };
          users.nimda      = import ./home-headless-server.nix;
          backupFileExtension = "backup";
        };
        nixpkgs.overlays = [
          (final: prev: {
            unstable = import nixpkgs-unstable {
              inherit (final) config;
              inherit (final.stdenv.hostPlatform) system;
            };
          })
        ];
        # up (GUI update app) intentionally omitted — headless servers have no display.
      };
    };
  };
}
