# home/dank-material-shell.nix
# DankMaterialShell (DMS) desktop shell (user layer), plus the polkit agent and
# removable-media automounter that GNOME Shell supplied implicitly and DMS does
# not replace.
# Active only when vexos.desktop.environment == "hyprland" — imported
# unconditionally by home-desktop.nix and gated internally, matching the shape
# of home/gnome-common.nix and the system-side DE modules.
#
# Why the Home Manager module and not the NixOS one: upstream ships both under
# the option path `programs.dank-material-shell`, but only the home module
# carries `settings` / `clipboardSettings` / `session` (the JSON surface the
# later customisation phase needs) and a systemd user service with
# restartIfChanged triggers. The NixOS module would install the shell binary
# system-wide with no settings surface — see flake.nix dmsBase, which imports it
# for its option declarations only and never sets `enable`.
{ pkgs, lib, inputs, osConfig, ... }:
{
  # Imports cannot be conditional — they are resolved before option values
  # exist — so this sits outside the mkIf below. The upstream module is inert
  # until programs.dank-material-shell.enable is set, so non-Hyprland desktops
  # are unaffected by its presence.
  imports = [ inputs.dms.homeModules.dank-material-shell ];

  config = lib.mkIf (osConfig.vexos.desktop.environment == "hyprland") {
    # ── DankMaterialShell ───────────────────────────────────────────────────
    # systemd.enable binds dms.service to config.wayland.systemd.target, which
    # resolves to graphical-session.target — activated by UWSM (see the comment
    # in modules/hyprland-desktop.nix; without UWSM this never starts).
    #
    # `settings` / `clipboardSettings` / `session` are deliberately left unset:
    # this is the stock shell, to establish a booting baseline. Theming, bar
    # layout, widgets and plugins are the follow-up customisation phase.
    programs.dank-material-shell = {
      enable                 = true;
      systemd.enable         = true;
      quickshell.package     = pkgs.quickshell;   # 0.3.0 in nixos-26.05
      dgop.package           = pkgs.dgop;         # set explicitly — no module default
      enableSystemMonitoring = true;              # dgop  — system/process widgets
      enableCalendarEvents   = true;              # khal  — calendar events
      enableDynamicTheming   = true;              # matugen — Material-You theming
      enableAudioWavelength  = true;              # cava  — audio visualiser
      enableVPN              = true;              # networkmanager (enabled system-side)
    };

    # ── Polkit authentication agent ─────────────────────────────────────────
    # GNOME Shell provided this; DMS does not. Without it, any action needing
    # authentication (mounting a system disk, some Flatpak operations) silently
    # fails with no prompt.
    services.hyprpolkitagent.enable = true;

    # ── Removable-media automount ───────────────────────────────────────────
    # GNOME Shell auto-mounted USB drives; DMS does not. Requires
    # services.udisks2 system-side (set in modules/hyprland-desktop.nix).
    services.udiskie = {
      enable    = true;
      automount = true;
      tray      = "auto";
    };

    # ── Seed a minimal hyprland.conf, once ──────────────────────────────────
    # Hyprland is otherwise unconfigured (autogenerated default). DMS's launcher,
    # clipboard, notification center, control center and lock are all `dms ipc
    # call` targets with no default bar button, so an unconfigured Hyprland gives
    # a shell you cannot open anything from. This copies the repo's minimal
    # DMS-focused config into place ONLY if the user has none yet; after first
    # boot the file is user-owned and nixos-rebuild never touches it again.
    # Same one-shot pattern as the vexos-init-* services in home-desktop.nix.
    home.activation.seedHyprlandConf =
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        target="$HOME/.config/hypr/hyprland.conf"
        if [ ! -e "$target" ]; then
          run mkdir -p "$HOME/.config/hypr"
          run cp ${../files/hypr/hyprland.conf} "$target"
          run chmod u+w "$target"
        fi
      '';
  };
}
