#!/usr/bin/env bash
# =============================================================================
# mergerfs-pool.sh — vexos-nix interactive mergerfs + SnapRAID pool manager
# Project: vexos-nix — Personal NixOS Flake
# Purpose: One menu for the "bulk NAS" storage tier on a server-role host: show
#          status, create the pool, add/remove a disk, destroy the pool, and run
#          SnapRAID sync/scrub. Invoked by `just mergerfs-pool`.
# Usage:   sudo bash scripts/mergerfs-pool.sh [action]   (menu when no action is given)
#          actions: status create add remove destroy sync scrub
#
# "Create" hands off to the sibling create-mergerfs-pool.sh. Add/remove/destroy
# edit the declarative /etc/nixos/storage-pool.nix that script writes (same
# format, parsed back here). Nothing takes effect at boot until you rebuild.
#
# Each menu action runs in a subshell: an error in one action returns to the menu.
# Destructive actions require typing 'storage'. Safe to abort with Ctrl-C.
# =============================================================================

set -uo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BOLD='\033[1m'; RESET='\033[0m'
die()  { echo -e "${RED}error:${RESET} $*" >&2; exit 1; }
warn() { echo -e "${YELLOW}warning:${RESET} $*" >&2; }
ok()   { echo -e "${GREEN}✓${RESET} $*"; }
hdr()  { echo ""; echo -e "${BOLD}── $* ──────────────────────────────────────────${RESET}"; }

# Resolve siblings via the UNRESOLVED path (see zfs-pool.sh for why).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STORAGE_POOL_NIX="${STORAGE_POOL_NIX:-/etc/nixos/storage-pool.nix}"
UNION_MNT="/storage"
CONFIRM_WORD="storage"

declare -a B_MNT=() B_UUID=() B_FS=()      # content disks (mergerfs branches)
declare -a P_MNT=() P_UUID=() P_FS=()      # SnapRAID parity disks
declare -a CANDIDATES=() CAND_DEV=() CAND_INFO=() SELECTED_BYID=()

# ---------- Generic helpers --------------------------------------------------

ask() { printf "%s" "$1"; read -r REPLY || die "input closed"; }

confirm_word() {
    echo "To proceed, type '$CONFIRM_WORD' exactly:"
    ask "> "
    [ "$REPLY" = "$CONFIRM_WORD" ] || die "confirmation mismatch — aborting (no changes made)"
}

pause() { printf "\nPress Enter to return to the menu... "; read -r _ || exit 0; }

run_action() { ( "$@" ); pause; }

rebuild_reminder() {
    echo ""
    echo "Apply with your normal rebuild (e.g. 'just rebuild') so the boot-time mounts"
    echo "match $STORAGE_POOL_NIX."
}

# ---------- storage-pool.nix: parse and write --------------------------------

# Print "mountpoint|uuid|fstype" for each entry in the list opened by line regex $1.
parse_entries() {
    awk -v start="$1" '
        $0 ~ start                 { f = 1; next }
        f && /^[[:space:]]*\];/    { f = 0 }
        f && /mountPoint/          { print }' "$STORAGE_POOL_NIX" \
        | sed -n 's|.*mountPoint = "\([^"]*\)"; device = "/dev/disk/by-uuid/\([^"]*\)"; fsType = "\([^"]*\)".*|\1\|\2\|\3|p'
}

load_pool() {
    B_MNT=(); B_UUID=(); B_FS=(); P_MNT=(); P_UUID=(); P_FS=()
    [ -f "$STORAGE_POOL_NIX" ] || return 0
    local m u f
    while IFS='|' read -r m u f; do
        B_MNT+=("$m"); B_UUID+=("$u"); B_FS+=("$f")
    done < <(parse_entries 'branches = [[]')
    while IFS='|' read -r m u f; do
        P_MNT+=("$m"); P_UUID+=("$u"); P_FS+=("$f")
    done < <(parse_entries 'parityDisks = [[]')
}

# Same output format as create-mergerfs-pool.sh, from the B_*/P_* arrays.
write_pool() {
    local j
    if [ -f "$STORAGE_POOL_NIX" ]; then
        cp -a "$STORAGE_POOL_NIX" "${STORAGE_POOL_NIX}.bak"
        warn "existing $STORAGE_POOL_NIX backed up to ${STORAGE_POOL_NIX}.bak"
    fi
    {
        echo "# /etc/nixos/storage-pool.nix"
        echo "# GENERATED by scripts/mergerfs-pool.sh on $(date '+%Y-%m-%d %H:%M:%S')."
        echo "# Re-running the script overwrites this file (prior version saved as .bak)."
        echo "# Host-generated (per-machine disk UUIDs) — do NOT commit to the vexos-nix repo."
        echo "{ ... }:"
        echo "{"
        echo "  vexos.server.nas.backend = \"mergerfs\";"
        echo ""
        echo "  vexos.server.storage.mergerfs = {"
        echo "    enable = true;"
        echo "    branches = ["
        for j in "${!B_MNT[@]}"; do
            echo "      { mountPoint = \"${B_MNT[$j]}\"; device = \"/dev/disk/by-uuid/${B_UUID[$j]}\"; fsType = \"${B_FS[$j]}\"; }"
        done
        echo "    ];"
        echo "  };"
        if [ "${#P_MNT[@]}" -gt 0 ]; then
            echo ""
            echo "  vexos.server.storage.snapraid = {"
            echo "    enable = true;"
            echo "    parityDisks = ["
            for j in "${!P_MNT[@]}"; do
                echo "      { mountPoint = \"${P_MNT[$j]}\"; device = \"/dev/disk/by-uuid/${P_UUID[$j]}\"; fsType = \"${P_FS[$j]}\"; }"
            done
            echo "    ];"
            echo "  };"
        fi
        echo "}"
    } > "$STORAGE_POOL_NIX" || die "could not write $STORAGE_POOL_NIX"
    ok "wrote $STORAGE_POOL_NIX"
}

require_pool() {
    load_pool
    [ "${#B_MNT[@]}" -gt 0 ] || die "no pool found in $STORAGE_POOL_NIX — create one first"
}

# Next free /mnt/<prefix><N> number given the existing mountpoints.
next_mount() {
    local prefix="$1" max=0 m n
    for m in "${B_MNT[@]}" "${P_MNT[@]}"; do
        if [[ "$m" =~ ^/mnt/${prefix}([0-9]+)$ ]]; then
            n="${BASH_REMATCH[1]}"
            [ "$n" -gt "$max" ] && max="$n"
        fi
    done
    echo "/mnt/${prefix}$((max+1))"
}

# ---------- Disk picker (same rules as zfs-pool.sh) --------------------------

# Kernel names of whole disks that belong to an imported ZFS pool (none if ZFS is absent).
zfs_member_disks() {
    command -v zpool >/dev/null 2>&1 || return 0
    local pool path dev parent
    while read -r pool; do
        while read -r path _; do
            [[ "$path" == /dev/* ]] || continue
            dev=$(readlink -f "$path") || continue
            parent=$(lsblk -no PKNAME "$dev" 2>/dev/null | head -1)
            basename "${parent:-$dev}"
        done < <(zpool status -P "$pool" 2>/dev/null | awk -v pool="$pool" '
            /^[[:space:]]*NAME[[:space:]]+STATE/ { cfg = 1; next }
            cfg && /^[[:space:]]*$/              { cfg = 0 }
            cfg && NF >= 2 && $1 != pool         { print $1, $2 }')
    done < <(zpool list -H -o name 2>/dev/null) | sort -u
}

enumerate_disks() {
    CANDIDATES=(); CAND_DEV=(); CAND_INFO=()
    local used byid dev base info tag uuid hidden=0 i u skip
    used=$(zfs_member_disks)
    while IFS= read -r byid; do
        [ -L "/dev/disk/by-id/$byid" ] || continue
        case "$byid" in
            *-part[0-9]*) continue ;;
            ata-*|nvme-*|scsi-*|wwn-*) ;;
            *) continue ;;
        esac
        dev=$(readlink -f "/dev/disk/by-id/$byid")
        base=$(basename "$dev")
        printf '%s\n' "${CAND_DEV[@]}" | grep -qx "$base" && continue   # alias of a disk already listed
        if lsblk -nr -o MOUNTPOINT "$dev" 2>/dev/null | grep -q .; then
            continue                                                    # mounted (OS, branches, parity, data)
        fi
        if echo "$used" | grep -qx "$base"; then
            hidden=$((hidden+1)); continue
        fi
        # a configured pool disk that happens to be unmounted right now
        uuid=$(blkid -s UUID -o value "$dev" 2>/dev/null || true)
        skip=0
        if [ -n "$uuid" ]; then
            for u in "${B_UUID[@]}" "${P_UUID[@]}"; do
                [ "$u" = "$uuid" ] && skip=1
            done
        fi
        if [ "$skip" -eq 1 ]; then hidden=$((hidden+1)); continue; fi
        info=$(lsblk -dno SIZE,MODEL,TRAN "$dev" 2>/dev/null | head -1)
        tag=""
        if [ -n "$(lsblk -nr -o FSTYPE "$dev" 2>/dev/null | grep -v '^$' | head -1)" ]; then
            tag="  [has existing data/filesystem]"
        fi
        CANDIDATES+=("$byid"); CAND_DEV+=("$base"); CAND_INFO+=("$info$tag")
    done < <(ls /dev/disk/by-id/ 2>/dev/null)

    [ "${#CANDIDATES[@]}" -gt 0 ] || die "no eligible disks found (every disk is mounted or already in a pool)"
    echo ""
    printf "  %-3s  %-50s  %-10s  %s\n" "#" "by-id" "device" "size / model / tran"
    printf "  %-3s  %-50s  %-10s  %s\n" "-" "-----" "------" "-------------------"
    for i in "${!CANDIDATES[@]}"; do
        printf "  %-3s  %-50s  %-10s  %s\n" "$((i+1))" "${CANDIDATES[$i]}" "${CAND_DEV[$i]}" "${CAND_INFO[$i]}"
    done
    [ "$hidden" -eq 0 ] || echo "  ($hidden disk(s) hidden because they already belong to a ZFS or mergerfs pool)"
    echo ""
}

# $1 = min, $2 = max (0 = no limit). Sets SELECTED_BYID.
select_disks() {
    local min="$1" max="$2" idx input seen valid
    while true; do
        ask "Select disks (comma- or space-separated numbers, e.g. '1 2'): "
        input="${REPLY//,/ }"
        SELECTED_BYID=(); seen=" "; valid=1
        for idx in $input; do
            if ! [[ "$idx" =~ ^[0-9]+$ ]] || [ "$idx" -lt 1 ] || [ "$idx" -gt "${#CANDIDATES[@]}" ]; then
                echo "  invalid number: $idx"; valid=0; break
            fi
            if [[ "$seen" == *" $idx "* ]]; then
                echo "  disk $idx listed twice"; valid=0; break
            fi
            seen="$seen$idx "
            SELECTED_BYID+=("/dev/disk/by-id/${CANDIDATES[$((idx-1))]}")
        done
        [ "$valid" -eq 1 ] || continue
        if [ "${#SELECTED_BYID[@]}" -lt "$min" ]; then
            echo "  select at least $min disk(s)"; continue
        fi
        if [ "$max" -gt 0 ] && [ "${#SELECTED_BYID[@]}" -gt "$max" ]; then
            echo "  select at most $max disk(s)"; continue
        fi
        return 0
    done
}

# $1 = by-id path, $2 = mountpoint, $3 = fstype. Wipes, formats, mounts; echoes the UUID.
format_and_mount() {
    local path="$1" mnt="$2" fs="$3" dev
    dev=$(readlink -f "$path")
    echo "  wipefs -a $dev" >&2
    wipefs -a "$dev" >/dev/null 2>&1 || warn "wipefs reported an issue on $dev"
    if [ "$fs" = "ext4" ]; then
        mkfs.ext4 -F "$dev" >/dev/null 2>&1 || die "mkfs.ext4 failed on $dev"
    else
        mkfs.xfs -f "$dev" >/dev/null 2>&1 || die "mkfs.xfs failed on $dev"
    fi
    mkdir -p "$mnt"
    mount "$dev" "$mnt" || die "mount $dev → $mnt failed"
    blkid -s UUID -o value "$dev"
}

# ---------- Actions ----------------------------------------------------------

action_status() {
    hdr "Pool status"
    load_pool
    if [ "${#B_MNT[@]}" -eq 0 ]; then
        echo "  No mergerfs pool is configured ($STORAGE_POOL_NIX)."
        return 0
    fi
    echo "  Pool mountpoint: $UNION_MNT"
    if findmnt -n "$UNION_MNT" >/dev/null 2>&1; then
        df -h "$UNION_MNT" | sed 's/^/  /'
    else
        echo "  (not mounted right now — run a rebuild or check 'systemctl status storage.mount')"
    fi
    local j
    echo ""
    echo "  Content disks:"
    for j in "${!B_MNT[@]}"; do
        printf "    %-14s UUID=%s  %s  " "${B_MNT[$j]}" "${B_UUID[$j]}" "${B_FS[$j]}"
        if findmnt -n "${B_MNT[$j]}" >/dev/null 2>&1; then
            df -h --output=size,used,avail,pcent "${B_MNT[$j]}" | tail -1
        else
            echo "NOT MOUNTED"
        fi
    done
    echo ""
    if [ "${#P_MNT[@]}" -gt 0 ]; then
        echo "  Parity disks (SnapRAID):"
        for j in "${!P_MNT[@]}"; do
            printf "    %-14s UUID=%s  %s  " "${P_MNT[$j]}" "${P_UUID[$j]}" "${P_FS[$j]}"
            if findmnt -n "${P_MNT[$j]}" >/dev/null 2>&1; then
                df -h --output=size,used,avail,pcent "${P_MNT[$j]}" | tail -1
            else
                echo "NOT MOUNTED"
            fi
        done
        if command -v snapraid >/dev/null 2>&1; then
            echo ""
            snapraid status 2>&1 | sed 's/^/  /' || true
        fi
    else
        echo "  No parity disks — the pool has NO redundancy."
    fi
}

action_create() {
    hdr "Create a new pool"
    [ -f "$SCRIPT_DIR/create-mergerfs-pool.sh" ] || die "create-mergerfs-pool.sh not found next to this script ($SCRIPT_DIR)"
    load_pool
    if [ "${#B_MNT[@]}" -gt 0 ]; then
        warn "a pool is already configured (${#B_MNT[@]} content disk(s)). Creating a new one REPLACES"
        warn "that configuration — the old disks keep their data but leave the pool."
        warn "To grow the existing pool, use 'Add a disk' instead."
        ask "Replace the existing pool configuration anyway? [y/N]: "
        case "${REPLY,,}" in
            y|yes) ;;
            *) die "cancelled — nothing changed" ;;
        esac
    fi
    bash "$SCRIPT_DIR/create-mergerfs-pool.sh"
}

action_add() {
    hdr "Add a disk to the pool"
    require_pool
    command -v mkfs.ext4 >/dev/null 2>&1 || die "mkfs.ext4 not found — e2fsprogs missing"
    echo "  1) Content disk — adds its space to the pool"
    echo "  2) Parity disk  — SnapRAID protection (must be at least as large as your largest content disk)"
    local role
    while true; do
        ask "Choice [1-2]: "
        role="$REPLY"
        case "$role" in 1|2) break ;; *) echo "  invalid" ;; esac
    done
    local fs="${B_FS[0]}"
    echo ""
    echo "The new disk will be ERASED and formatted ($fs)."
    enumerate_disks
    select_disks 1 1
    local path="${SELECTED_BYID[0]}" dev size largest=0 s j
    dev=$(readlink -f "$path")

    if [ "$role" = "2" ]; then
        for j in "${!B_MNT[@]}"; do
            s=$(lsblk -bdno SIZE "/dev/disk/by-uuid/${B_UUID[$j]}" 2>/dev/null | head -1)
            [[ "$s" =~ ^[0-9]+$ ]] && [ "$s" -gt "$largest" ] && largest="$s"
        done
        size=$(lsblk -bdno SIZE "$dev" | head -1)
        if [ "$largest" -gt 0 ] && [ "$size" -lt "$largest" ]; then
            die "parity disk ($size bytes) is smaller than the largest content disk ($largest bytes) — SnapRAID needs it to be at least as large"
        fi
    fi

    local prefix="disk"; [ "$role" = "2" ] && prefix="parity"
    local mnt; mnt=$(next_mount "$prefix")
    echo ""
    echo "  New disk   : $path"
    echo "  Role       : $([ "$role" = "1" ] && echo content || echo parity)"
    echo "  Mountpoint : $mnt"
    echo ""
    echo -e "${RED}ALL EXISTING DATA on this disk will be destroyed.${RESET}"
    confirm_word

    local uuid
    uuid=$(format_and_mount "$path" "$mnt" "$fs")
    [ -n "$uuid" ] || die "could not read the new filesystem's UUID"
    ok "$mnt mounted (UUID=$uuid)"
    if [ "$role" = "1" ]; then
        B_MNT+=("$mnt"); B_UUID+=("$uuid"); B_FS+=("$fs")
    else
        P_MNT+=("$mnt"); P_UUID+=("$uuid"); P_FS+=("$fs")
    fi
    write_pool
    rebuild_reminder
    if [ "$role" = "2" ]; then
        echo "After the rebuild, build the new parity with:  just mergerfs-pool sync"
    fi
}

action_remove() {
    hdr "Remove a disk from the pool"
    require_pool
    local -a role=() mnts=() uuids=()
    local j i sel
    for j in "${!B_MNT[@]}"; do role+=("content"); mnts+=("${B_MNT[$j]}"); uuids+=("${B_UUID[$j]}"); done
    for j in "${!P_MNT[@]}"; do role+=("parity");  mnts+=("${P_MNT[$j]}"); uuids+=("${P_UUID[$j]}"); done
    echo ""
    for i in "${!mnts[@]}"; do
        printf "  %d) %-8s %-14s UUID=%s  " "$((i+1))" "${role[$i]}" "${mnts[$i]}" "${uuids[$i]}"
        if findmnt -n "${mnts[$i]}" >/dev/null 2>&1; then
            df -h --output=used "${mnts[$i]}" | tail -1 | sed 's/^ *//; s/$/ used/'
        else
            echo "(not mounted)"
        fi
    done
    echo ""
    while true; do
        ask "Disk to remove [1-${#mnts[@]}]: "
        sel="$REPLY"
        if [[ "$sel" =~ ^[0-9]+$ ]] && [ "$sel" -ge 1 ] && [ "$sel" -le "${#mnts[@]}" ]; then break; fi
        echo "  invalid"
    done
    local r="${role[$((sel-1))]}" m="${mnts[$((sel-1))]}"
    if [ "$r" = "content" ] && [ "${#B_MNT[@]}" -le 1 ]; then
        die "this is the last content disk — use 'Destroy the pool' instead"
    fi

    echo ""
    if [ "$r" = "content" ]; then
        echo -e "${YELLOW}Files on $m will no longer appear in $UNION_MNT once this is applied.${RESET}"
        echo "The data itself stays on the disk (it is NOT erased). Copy anything you still"
        echo "need into the pool first, or mount the disk elsewhere to read it."
        if [ "${#P_MNT[@]}" -gt 0 ]; then
            echo "SnapRAID names data disks d1, d2, ... by position: after removing a disk, run"
            echo "'just mergerfs-pool sync' and check 'snapraid status' for renumbering warnings."
        fi
    else
        echo -e "${YELLOW}Removing a parity disk lowers (or, if it is the last, removes) SnapRAID protection.${RESET}"
    fi
    confirm_word

    local -a nm=() nu=() nf=()
    if [ "$r" = "content" ]; then
        for j in "${!B_MNT[@]}"; do
            [ "${B_MNT[$j]}" = "$m" ] || { nm+=("${B_MNT[$j]}"); nu+=("${B_UUID[$j]}"); nf+=("${B_FS[$j]}"); }
        done
        B_MNT=("${nm[@]}"); B_UUID=("${nu[@]}"); B_FS=("${nf[@]}")
    else
        for j in "${!P_MNT[@]}"; do
            [ "${P_MNT[$j]}" = "$m" ] || { nm+=("${P_MNT[$j]}"); nu+=("${P_UUID[$j]}"); nf+=("${P_FS[$j]}"); }
        done
        P_MNT=("${nm[@]}"); P_UUID=("${nu[@]}"); P_FS=("${nf[@]}")
    fi
    write_pool
    rebuild_reminder
    echo "After the rebuild $m is no longer managed; if it is still mounted, run: sudo umount $m"
}

action_destroy() {
    hdr "Destroy the pool"
    require_pool
    local wipe
    echo ""
    echo "  Pool mountpoint : $UNION_MNT"
    echo "  Content disks   : ${B_MNT[*]}"
    [ "${#P_MNT[@]}" -eq 0 ] || echo "  Parity disks    : ${P_MNT[*]}"
    echo ""
    echo -e "${RED}This unmounts the pool and removes it from $STORAGE_POOL_NIX.${RESET}"
    echo "Anything using $UNION_MNT (Samba/NFS shares, containers, services) will lose it."
    ask "Also ERASE the disks (wipefs)? Default is no — the data stays on each disk [y/N]: "
    wipe="${REPLY,,}"
    case "$wipe" in y|yes) wipe=yes ;; *) wipe=no ;; esac
    if [ "$wipe" = "yes" ]; then
        echo -e "${RED}ALL DATA on every pool disk will be destroyed.${RESET}"
    fi
    confirm_word

    if findmnt -n "$UNION_MNT" >/dev/null 2>&1; then
        umount "$UNION_MNT" || die "could not unmount $UNION_MNT — stop whatever is using it (try: lsof +D $UNION_MNT) and retry"
        ok "$UNION_MNT unmounted"
    fi
    local -a all=("${B_MNT[@]}" "${P_MNT[@]}") devs=()
    local m dev
    for m in "${all[@]}"; do
        dev=$(findmnt -n -o SOURCE "$m" 2>/dev/null || true)
        [ -n "$dev" ] && devs+=("$dev")
        if findmnt -n "$m" >/dev/null 2>&1; then
            umount "$m" || die "could not unmount $m (see message above)"
            ok "$m unmounted"
        fi
    done
    if [ "$wipe" = "yes" ]; then
        for dev in "${devs[@]}"; do
            echo "  wipefs -a $dev"
            wipefs -a "$dev" >/dev/null || warn "wipefs failed on $dev"
        done
    fi
    if [ -f "$STORAGE_POOL_NIX" ]; then
        cp -a "$STORAGE_POOL_NIX" "${STORAGE_POOL_NIX}.bak"
        rm -f "$STORAGE_POOL_NIX"
        ok "removed $STORAGE_POOL_NIX (copy kept as ${STORAGE_POOL_NIX}.bak)"
    fi
    rebuild_reminder
    echo "Until you rebuild, the old mounts are still declared and return at the next boot."
}

require_snapraid() {
    load_pool
    [ "${#P_MNT[@]}" -gt 0 ] || die "no parity disks configured — SnapRAID is not set up on this pool"
    command -v snapraid >/dev/null 2>&1 || die "snapraid not found — rebuild first so SnapRAID is installed"
    [ -f /etc/snapraid.conf ] || die "/etc/snapraid.conf not found — rebuild first"
}

action_sync() {
    hdr "SnapRAID sync (refresh parity)"
    require_snapraid
    echo "  This can take hours on a large pool. Ctrl-C stops it safely; run it again to resume."
    snapraid sync
}

action_scrub() {
    hdr "SnapRAID scrub (check for silent corruption)"
    require_snapraid
    echo "  This reads part of the array and can take hours. Ctrl-C stops it safely."
    snapraid scrub
}

# ---------- Preconditions ----------------------------------------------------
[ "$(id -u)" -eq 0 ] || die "must be run as root (use 'just mergerfs-pool', which calls sudo)"
for t in lsblk blkid wipefs findmnt; do
    command -v "$t" >/dev/null 2>&1 || die "$t not found — util-linux missing"
done

# ---------- Direct action: `just mergerfs-pool <action>` ---------------------
if [ $# -gt 0 ]; then
    case "$1" in
        status|create|add|remove|destroy|sync|scrub)
            "action_$1"; exit $? ;;
        *)  die "unknown action '$1' (status, create, add, remove, destroy, sync, scrub)" ;;
    esac
fi

# ---------- Menu -------------------------------------------------------------
while true; do
    hdr "mergerfs + SnapRAID pool manager"
    echo "  1) Show pool status and disk usage"
    echo "  2) Create a new pool                (format disks and set up /storage)"
    echo "  3) Add a disk to the pool           (more space, or a SnapRAID parity disk)"
    echo "  4) Remove a disk from the pool      (its data stays on the disk)"
    echo "  5) Destroy the pool                 (unmount and remove it; optionally erase the disks)"
    echo "  6) Run a SnapRAID sync now          (refresh parity after files changed)"
    echo "  7) Run a SnapRAID scrub now         (check for silent corruption)"
    echo "  0) Quit"
    echo ""
    ask "Choice [0-7]: "
    case "$REPLY" in
        1)  run_action action_status ;;
        2)  run_action action_create ;;
        3)  run_action action_add ;;
        4)  run_action action_remove ;;
        5)  run_action action_destroy ;;
        6)  run_action action_sync ;;
        7)  run_action action_scrub ;;
        0|q|Q) exit 0 ;;
        *)  echo "  invalid" ;;
    esac
done
